# Controller generated by Typus, use it to extend admin functionality.
class Admin::SubscribersController < Admin::MasterController

  def send_letter
    email_list = Subscriber.all.map {|s| s.email}.join(",")
    Contact.deliver_subscriber_list(email_list)
    flash[:notice] = "Пошту надіслано"
    redirect_to :back
  end

end