# Controller generated by Typus, use it to extend admin functionality.
class Admin::WorksController < Admin::MasterController

def sort
  render :layout => false
end

def sort_items
@list = Work.send(params[:method])
  @list.each do | item |
    item.position = params["#{params[:method]}-list"].index(item.id.to_s)+1
    item.save
  end
render :nothing => true
end

end