development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: studio
  pool: 5
  username: voronin
  password: antidote
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: studio
  pool: 5
  username: root
  password: casper12345
  host: localhost
